BASE_URL = 'https://stellarburgers.nomoreparties.site/api/'
CREATE_USER = BASE_URL + 'auth/register'
LOGIN_USER = BASE_URL + 'auth/login'
CHANGE_USER = BASE_URL + 'auth/user'
CREATE_ORDER = BASE_URL + 'orders'
GET_INGREDIENTS = BASE_URL + 'ingredients'